// Curated emoji set. `e` = emoji, `k` = keywords for searching.
const EMOJIS: Array<{ e: string; k: string[] }> = [
  // Smileys
  { e: "😀", k: ["grin", "smile", "happy"] },
  { e: "😃", k: ["smiley", "happy", "joy"] },
  { e: "😄", k: ["smile", "happy"] },
  { e: "😁", k: ["beam", "grin", "happy"] },
  { e: "😆", k: ["laugh", "haha"] },
  { e: "😅", k: ["sweat", "smile", "phew"] },
  { e: "🤣", k: ["rofl", "laugh", "lol"] },
  { e: "😂", k: ["joy", "cry", "lol", "tears"] },
  { e: "🙂", k: ["slight", "smile"] },
  { e: "🙃", k: ["upside", "down"] },
  { e: "😉", k: ["wink"] },
  { e: "😊", k: ["blush", "happy"] },
  { e: "😇", k: ["angel", "halo"] },
  { e: "🥰", k: ["love", "hearts"] },
  { e: "😍", k: ["heart", "eyes", "love"] },
  { e: "🤩", k: ["star", "struck", "wow"] },
  { e: "😘", k: ["kiss"] },
  { e: "😗", k: ["kiss"] },
  { e: "😚", k: ["kiss", "closed"] },
  { e: "😙", k: ["kiss", "smile"] },
  { e: "🥲", k: ["smile", "tear"] },
  { e: "😋", k: ["yum", "tasty"] },
  { e: "😛", k: ["tongue"] },
  { e: "😜", k: ["wink", "tongue"] },
  { e: "🤪", k: ["zany", "crazy"] },
  { e: "😝", k: ["tongue", "squint"] },
  { e: "🤑", k: ["money", "rich"] },
  { e: "🤗", k: ["hug"] },
  { e: "🤭", k: ["oops", "giggle"] },
  { e: "🤫", k: ["shush", "quiet"] },
  { e: "🤔", k: ["think", "thinking", "hmm"] },
  { e: "🤐", k: ["zip", "quiet"] },
  { e: "🤨", k: ["raised", "brow", "skeptical"] },
  { e: "😐", k: ["neutral"] },
  { e: "😑", k: ["expressionless"] },
  { e: "😶", k: ["mute", "silence"] },
  { e: "😏", k: ["smirk"] },
  { e: "😒", k: ["unamused", "meh"] },
  { e: "🙄", k: ["eye", "roll"] },
  { e: "😬", k: ["grimace", "yikes"] },
  { e: "🤥", k: ["lying", "pinocchio"] },
  { e: "😌", k: ["relieved", "calm"] },
  { e: "😔", k: ["pensive", "sad"] },
  { e: "😪", k: ["sleepy", "tired"] },
  { e: "🤤", k: ["drool"] },
  { e: "😴", k: ["sleep", "zzz"] },
  { e: "😷", k: ["mask", "sick"] },
  { e: "🤒", k: ["fever", "sick"] },
  { e: "🤕", k: ["bandage", "hurt"] },
  { e: "🤢", k: ["nauseated", "sick"] },
  { e: "🤮", k: ["vomit"] },
  { e: "🤧", k: ["sneeze"] },
  { e: "🥵", k: ["hot"] },
  { e: "🥶", k: ["cold"] },
  { e: "🥴", k: ["woozy", "drunk"] },
  { e: "😵", k: ["dizzy"] },
  { e: "🤯", k: ["mind", "blown"] },
  { e: "🤠", k: ["cowboy"] },
  { e: "🥳", k: ["party"] },
  { e: "😎", k: ["cool", "sunglasses"] },
  { e: "🤓", k: ["nerd", "glasses"] },
  { e: "🧐", k: ["monocle", "inspect"] },
  { e: "😕", k: ["confused"] },
  { e: "😟", k: ["worried"] },
  { e: "🙁", k: ["frown", "sad"] },
  { e: "☹️", k: ["frown", "sad"] },
  { e: "😮", k: ["surprised"] },
  { e: "😯", k: ["hushed"] },
  { e: "😲", k: ["astonished"] },
  { e: "😳", k: ["flushed"] },
  { e: "🥺", k: ["pleading", "sad"] },
  { e: "😦", k: ["frown", "open"] },
  { e: "😧", k: ["anguish"] },
  { e: "😨", k: ["fear"] },
  { e: "😰", k: ["anxious", "sweat"] },
  { e: "😥", k: ["sad", "relieved"] },
  { e: "😢", k: ["cry", "sad", "tear"] },
  { e: "😭", k: ["sob", "cry", "loud"] },
  { e: "😱", k: ["scream", "shock"] },
  { e: "😖", k: ["confounded"] },
  { e: "😣", k: ["persevere"] },
  { e: "😞", k: ["disappointed"] },
  { e: "😓", k: ["sweat", "downcast"] },
  { e: "😩", k: ["weary"] },
  { e: "😫", k: ["tired"] },
  { e: "🥱", k: ["yawn"] },
  { e: "😤", k: ["triumph", "frustrate"] },
  { e: "😡", k: ["pout", "rage", "angry"] },
  { e: "😠", k: ["angry"] },
  { e: "🤬", k: ["curse", "swear"] },
  { e: "😈", k: ["devil", "smile"] },
  { e: "👿", k: ["devil", "angry"] },
  { e: "💀", k: ["skull", "dead"] },
  { e: "☠️", k: ["skull", "death"] },
  { e: "💩", k: ["poop", "shit"] },
  { e: "🤡", k: ["clown"] },
  { e: "👻", k: ["ghost", "spooky"] },
  { e: "👽", k: ["alien"] },
  { e: "👾", k: ["space", "invader"] },
  { e: "🤖", k: ["robot"] },
  { e: "🎃", k: ["pumpkin", "halloween"] },

  // Hand & body
  { e: "👍", k: ["thumbs", "up", "yes", "approve"] },
  { e: "👎", k: ["thumbs", "down", "no"] },
  { e: "👌", k: ["ok", "okay"] },
  { e: "🤌", k: ["pinched", "italian"] },
  { e: "🤏", k: ["pinch", "small"] },
  { e: "✌️", k: ["peace", "victory"] },
  { e: "🤞", k: ["fingers", "crossed", "luck"] },
  { e: "🤟", k: ["love", "you"] },
  { e: "🤘", k: ["rock", "horns"] },
  { e: "🤙", k: ["call", "shaka"] },
  { e: "👈", k: ["left", "point"] },
  { e: "👉", k: ["right", "point"] },
  { e: "👆", k: ["up", "point"] },
  { e: "🖕", k: ["middle", "finger"] },
  { e: "👇", k: ["down", "point"] },
  { e: "☝️", k: ["index", "up"] },
  { e: "✋", k: ["raise", "stop"] },
  { e: "🤚", k: ["raise", "back"] },
  { e: "🖐️", k: ["splayed"] },
  { e: "🖖", k: ["spock", "vulcan"] },
  { e: "👋", k: ["wave", "hi", "hello"] },
  { e: "🤝", k: ["handshake", "deal"] },
  { e: "👏", k: ["clap"] },
  { e: "🙌", k: ["raised", "hands", "praise"] },
  { e: "👐", k: ["open", "hands"] },
  { e: "🤲", k: ["palms", "together"] },
  { e: "🙏", k: ["pray", "thanks"] },
  { e: "✍️", k: ["write", "writing"] },
  { e: "💪", k: ["muscle", "strong"] },
  { e: "👀", k: ["eyes", "look"] },
  { e: "🧠", k: ["brain"] },
  { e: "👅", k: ["tongue"] },
  { e: "👄", k: ["mouth"] },

  // Hearts & symbols
  { e: "❤️", k: ["red", "heart", "love"] },
  { e: "🧡", k: ["orange", "heart"] },
  { e: "💛", k: ["yellow", "heart"] },
  { e: "💚", k: ["green", "heart"] },
  { e: "💙", k: ["blue", "heart"] },
  { e: "💜", k: ["purple", "heart"] },
  { e: "🖤", k: ["black", "heart"] },
  { e: "🤍", k: ["white", "heart"] },
  { e: "🤎", k: ["brown", "heart"] },
  { e: "💔", k: ["broken", "heart"] },
  { e: "❣️", k: ["heart", "exclam"] },
  { e: "💕", k: ["two", "hearts"] },
  { e: "💞", k: ["revolving", "hearts"] },
  { e: "💓", k: ["beating", "heart"] },
  { e: "💗", k: ["growing", "heart"] },
  { e: "💖", k: ["sparkling", "heart"] },
  { e: "💘", k: ["arrow", "heart", "cupid"] },
  { e: "💝", k: ["gift", "heart"] },
  { e: "💟", k: ["heart", "decoration"] },
  { e: "♥️", k: ["heart", "suit"] },
  { e: "💯", k: ["hundred", "100", "perfect"] },
  { e: "💢", k: ["anger"] },
  { e: "💥", k: ["boom", "collision"] },
  { e: "💫", k: ["dizzy", "star"] },
  { e: "💦", k: ["sweat", "drops"] },
  { e: "💨", k: ["dash", "wind"] },
  { e: "🕳️", k: ["hole"] },
  { e: "💣", k: ["bomb"] },
  { e: "💬", k: ["speech", "bubble"] },
  { e: "💭", k: ["thought"] },
  { e: "🗯️", k: ["anger", "bubble"] },
  { e: "💤", k: ["zzz", "sleep"] },
  { e: "✨", k: ["sparkles", "shiny"] },
  { e: "⭐", k: ["star"] },
  { e: "🌟", k: ["glowing", "star"] },
  { e: "🌠", k: ["shooting", "star"] },
  { e: "🔥", k: ["fire", "lit", "hot"] },
  { e: "✅", k: ["check", "yes", "done"] },
  { e: "❌", k: ["x", "no", "wrong"] },
  { e: "⚠️", k: ["warning"] },
  { e: "❓", k: ["question"] },
  { e: "❗", k: ["exclamation"] },
  { e: "✔️", k: ["check", "mark"] },
  { e: "➕", k: ["plus"] },
  { e: "➖", k: ["minus"] },
  { e: "➡️", k: ["arrow", "right"] },
  { e: "⬅️", k: ["arrow", "left"] },
  { e: "⬆️", k: ["arrow", "up"] },
  { e: "⬇️", k: ["arrow", "down"] },
  { e: "🔄", k: ["refresh", "reload"] },

  // Animals & food (small)
  { e: "🐶", k: ["dog", "puppy"] },
  { e: "🐱", k: ["cat", "kitty"] },
  { e: "🦊", k: ["fox"] },
  { e: "🐻", k: ["bear"] },
  { e: "🐼", k: ["panda"] },
  { e: "🐨", k: ["koala"] },
  { e: "🐯", k: ["tiger"] },
  { e: "🦁", k: ["lion"] },
  { e: "🐮", k: ["cow"] },
  { e: "🐷", k: ["pig"] },
  { e: "🐸", k: ["frog"] },
  { e: "🐵", k: ["monkey"] },
  { e: "🐔", k: ["chicken"] },
  { e: "🐧", k: ["penguin"] },
  { e: "🐦", k: ["bird"] },
  { e: "🦆", k: ["duck"] },
  { e: "🦉", k: ["owl"] },
  { e: "🐺", k: ["wolf"] },
  { e: "🐗", k: ["boar"] },
  { e: "🐴", k: ["horse"] },
  { e: "🦄", k: ["unicorn"] },
  { e: "🐝", k: ["bee"] },
  { e: "🐛", k: ["bug", "worm"] },
  { e: "🦋", k: ["butterfly"] },
  { e: "🐌", k: ["snail"] },
  { e: "🐞", k: ["ladybug"] },
  { e: "🐢", k: ["turtle"] },
  { e: "🐍", k: ["snake"] },
  { e: "🦀", k: ["crab"] },
  { e: "🐙", k: ["octopus"] },
  { e: "🐳", k: ["whale"] },
  { e: "🐬", k: ["dolphin"] },
  { e: "🐟", k: ["fish"] },
  { e: "🦈", k: ["shark"] },
  { e: "🍎", k: ["apple", "red"] },
  { e: "🍌", k: ["banana"] },
  { e: "🍇", k: ["grapes"] },
  { e: "🍉", k: ["watermelon"] },
  { e: "🍊", k: ["orange"] },
  { e: "🍓", k: ["strawberry"] },
  { e: "🍒", k: ["cherry"] },
  { e: "🍑", k: ["peach"] },
  { e: "🍍", k: ["pineapple"] },
  { e: "🥝", k: ["kiwi"] },
  { e: "🥑", k: ["avocado"] },
  { e: "🍅", k: ["tomato"] },
  { e: "🥕", k: ["carrot"] },
  { e: "🌽", k: ["corn"] },
  { e: "🍞", k: ["bread"] },
  { e: "🥐", k: ["croissant"] },
  { e: "🥨", k: ["pretzel"] },
  { e: "🧀", k: ["cheese"] },
  { e: "🍔", k: ["burger"] },
  { e: "🍟", k: ["fries"] },
  { e: "🍕", k: ["pizza"] },
  { e: "🌭", k: ["hotdog"] },
  { e: "🥪", k: ["sandwich"] },
  { e: "🌮", k: ["taco"] },
  { e: "🌯", k: ["burrito"] },
  { e: "🍳", k: ["egg", "cooking"] },
  { e: "🍣", k: ["sushi"] },
  { e: "🍙", k: ["rice", "ball"] },
  { e: "🍜", k: ["ramen", "noodles"] },
  { e: "🍰", k: ["cake"] },
  { e: "🎂", k: ["birthday", "cake"] },
  { e: "🍪", k: ["cookie"] },
  { e: "🍫", k: ["chocolate"] },
  { e: "🍬", k: ["candy"] },
  { e: "🍭", k: ["lollipop"] },
  { e: "☕", k: ["coffee", "hot"] },
  { e: "🍵", k: ["tea"] },
  { e: "🍺", k: ["beer"] },
  { e: "🍷", k: ["wine"] },
  { e: "🥂", k: ["champagne", "cheers"] },
  { e: "🍾", k: ["bottle", "champagne"] },

  // Tech & objects
  { e: "💻", k: ["laptop", "computer"] },
  { e: "🖥️", k: ["desktop", "computer"] },
  { e: "⌨️", k: ["keyboard"] },
  { e: "🖱️", k: ["mouse"] },
  { e: "🖨️", k: ["printer"] },
  { e: "📱", k: ["phone", "mobile"] },
  { e: "📷", k: ["camera"] },
  { e: "🎥", k: ["movie", "camera"] },
  { e: "🎙️", k: ["mic", "studio"] },
  { e: "🎧", k: ["headphones"] },
  { e: "🔌", k: ["plug"] },
  { e: "🔋", k: ["battery"] },
  { e: "💾", k: ["floppy", "save"] },
  { e: "💿", k: ["cd"] },
  { e: "📀", k: ["dvd"] },
  { e: "📦", k: ["package", "box"] },
  { e: "📁", k: ["folder"] },
  { e: "📄", k: ["file", "page"] },
  { e: "📝", k: ["memo", "note"] },
  { e: "📌", k: ["pin"] },
  { e: "📍", k: ["location"] },
  { e: "🔑", k: ["key"] },
  { e: "🔒", k: ["lock"] },
  { e: "🔓", k: ["unlock"] },
  { e: "🔔", k: ["bell", "notification"] },
  { e: "🔕", k: ["mute", "bell"] },
  { e: "🛠️", k: ["tools", "hammer", "wrench"] },
  { e: "🔧", k: ["wrench"] },
  { e: "🔨", k: ["hammer"] },
  { e: "⚙️", k: ["gear", "settings"] },
  { e: "🚀", k: ["rocket", "launch"] },
  { e: "🐛", k: ["bug"] },
  { e: "🎉", k: ["party", "tada", "celebrate"] },
  { e: "🎊", k: ["confetti"] },
  { e: "🎁", k: ["gift", "present"] },
  { e: "🏆", k: ["trophy", "win"] },
  { e: "🥇", k: ["gold", "medal"] },
  { e: "🥈", k: ["silver", "medal"] },
  { e: "🥉", k: ["bronze", "medal"] },
  { e: "🎯", k: ["target", "bullseye"] },
  { e: "💡", k: ["idea", "bulb", "light"] },
  { e: "📚", k: ["books"] },
  { e: "📖", k: ["book", "open"] },
  { e: "🔖", k: ["bookmark"] },
  { e: "💰", k: ["money", "bag"] },
  { e: "💸", k: ["cash", "fly"] },
  { e: "💳", k: ["card", "credit"] },
  { e: "💎", k: ["gem", "diamond"] },
]

export default EMOJIS
